language: go
env:
  global:
    - "GIT_NAME=Martin Sivak"
    - "GIT_EMAIL=mars@montik.net"
    - "SOURCE_DIR=public"
    - "DEPLOY_BRANCH=master"
    - "SSH_KEY=deploy.key"
go:
  - "1.5.1"
install: true
before_script:
  - go get  -u -v github.com/spf13/hugo
script:
  - hugo
after-success:
  - openssl aes-256-cbc -K $encrypted_0ef8d2efe080_key -iv $encrypted_0ef8d2efe080_iv -in deploy.key.enc -out deploy.key -d
  - cp CNAME public/
  - "[ -r index.html ] && cp index.html public/"
  - scripts/deploy.sh

